name: PixplazeServerTweaks
version: '${project.version}'
main: com.pixplaze.plugin.PixplazeServerTweaks
api-version: 1.18
authors: [ Ki$$Ka, emberati ]

commands:
  tweak:
    description: Handling with pixplaze server tweaks
    usage: /tweak <option> <value>